### PR TITLE
Update the jupyiter notebook links in example workflows section

### PR DESCRIPTION
**Pull request by jpurusho65**

### CODE REVIEW

**Review by kenxu95 — APPROVED** [review]
Nice!

**Comment by vsreekanti** [comment]
@jpurusho65, sorry for the confusion, but when I said on GitHub, I actually meant here: https://github.com/aqueducthq/aqueduct/tree/main/examples

These docs are autogenerated from those notebooks, so the links need to be fixed there rather than here. If the links are wrong in the example notebooks, then they will be clobbered the next time these docs are autogenerated.

**Comment by jpurusho65** [comment]
> @jpurusho65, sorry for the confusion, but when I said on GitHub, I actually meant here: https://github.com/aqueducthq/aqueduct/tree/main/examples
> 
> These docs are autogenerated from those notebooks, so the links need to be fixed there rather than here. If the links are wrong in the example notebooks, then they will be clobbered the next time these docs are autogenerated.

No worries Vikram, I changed .md files from which the documentation is generated.

**Comment by vsreekanti** [comment]
The `.md` files are actually autogenerated themselves. We use a Python script to turn the `.ipynb` files I linked above into the `.md` files that are here. Since the source `.ipynb` files are not changed (e.g., [this doc](https://github.com/aqueducthq/aqueduct/blob/main/examples/churn_prediction/Customer%20Churn%20Prediction.ipynb) still has a broken link), during the next release process, the on-call engineer will use the script to autogenerate the notebook files, update the documentation here, and the links will be broken again.

Let me know if that makes sense or if you have any questions!

**Pull request merged**
