### PR TITLE
0.1.9 release

### PR DESCRIPTION
**Pull request by likawind**

### CODE REVIEW

**Review by cw75 — COMMENTED** [review]
@likawind we haven't updated any example notebook in the last month, but there seems to be a lot of changes in two of the notebooks. Not sure why.

**Comment by likawind** [comment]
@cw75 Idk if it's due to version mismatches between my generating package vs the original. Looks like the main difference is the html vs raw table formatting. The preview looks fine though

**Comment by likawind** [comment]
An option is to revert these two files, but maybe it's safer to go with current version in case there's any change in the workflow?

**Comment by cw75** [comment]
@likawind Yeah if you double checked that your local version of these two files in the aqueduct repo matches exactly as the remote versions [here](https://github.com/aqueducthq/aqueduct/tree/main/examples), let's go with this.

**Review by cw75 — APPROVED** [review]

**Pull request merged**
