### PR TITLE
Update documentation for 0.0.9 release

### PR DESCRIPTION
**Pull request by cw75**
I think there are a bit of formatting issues for the newly added wine prediction notebook's documentation. @vsreekanti

### CODE REVIEW

**Comment by vsreekanti** [comment]
What is the formatting issue?

**Comment by cw75** [comment]
@vsreekanti I opened it in Jupyter and compared two versions and I think it's fine. I originally thought the `^` in the middle was some kind of formatting issue, but I think we meant "above"...

**Comment by vsreekanti** [comment]
Oh, I see, yes this is the new demo notebook. Let's remove that from the documentation for now. It's meant to be presented, not read.

**Comment by cw75** [comment]
Oh I see I'll remove this then. Could you approve.

**Review by vsreekanti — APPROVED** [review]

**Pull request merged**
